language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements/dev.txt

script:
  - "PYTHONPATH=rmotr_sakila django-admin runtests"
